backend:
  name: git-gateway
  branch: master
# publish_mode: editorial_workflow
site_url: "https://idrc.netlify.com"
media_folder: "src/images"
public_folder: "/images"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Homepage"
        delete: false
        file: "src/index.md"
        slug: "{{slug}}"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/home.njk"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
          - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Sections"
            name: "sections"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string", required: true}
              - {label: "Content", name: "content", widget: "markdown", required: true}
              - {label: "Text Colour", name: "textColour", widget: "string", required: false}
              - {label: "Background Colour", name: "backgroundColour", widget: "string", required: false}
              - {label: "Border Colour", name: "borderColour", widget: "string", required: false}
              - {label: "Image", name: "image", widget: "string", required: false}
              - {label: "Image (2x)", name: "image2x", widget: "string", required: false}
              - {label: "Image Alternative Text", name: "imageAltText", widget: "string", required: false}
              - {label: "Image Order", name: "imageOrder", widget: "string", required: false} # start or end
              - {label: "Image Order (Desktop)", name: "imageOrderDesktop", widget: "string", required: false} # auto or swap
              - {label: "Image Shadow", name: "imageShadow", widget: "string", required: false} # TODO: Figure out shadow options
              - {label: "Desktop Width", name: "desktopWidth", widget: "string", required: false} # half, full, or full-bleed
  - name: "generic_pages"
    label: "Generic Pages"
    folder: "src/pages"
    slug: "{{slug}}"
    preview_path: "pages/{{slug}}"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/page.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Custom Permalink (Pattern: '/your-slug/index.html')", name: "permalink", widget: "string", required: false}
      - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
      - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Globals"
    name: "globals"
    files:
      - label: "Site Data"
        name: "site_data"
        delete: false
        file: "src/_data/site.json"
        fields:
          - {label: "Site Titl", name: "title", widget: "string"}
          - {label: "Site Url", name: "url", widget: "string"}

      